### ISSUE TITLE
Error 1045 -- No interruptions and running as root user

### ISSUE THREAD

**Issue by al3x-edge** [geerlingguy/ansible-role-mysql#121]
Getting the error 1045 while just trying to run the role on as VPS on Vultr.  The playbook is being run for the first time and without interruptions until this point.  The role is being run as a root user.  `mysql_root_password` is being set and `mysql_root_password_update` is set to `yes`.  The `.my.cnf` file is being created in the user directory correctly.

```
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

Initially thought this was an issue with Ubuntu 16.04 (was testing), but seems to simply be from the switch to this role instead of another one.

**Comment by geerlingguy** [comment]
@al3x-edge - This role assumes you used the role to set up the VM/server in the first place; if not, then the task that tries to update the password (or perform any other operation in preparation) will fail because the proper password isn't stored inside `{{ mysql_user_home }}/.my.cnf`.

If you're switching to this role from another, you'll need to manually create that file with the root password in it first.

**Comment by al3x-edge** [comment]
@geerlingguy Thanks 👍  Apologies on the false bug report and appreciate the help. I'll update the recipes.
