### ISSUE TITLE
Migrate existing configuration to role

### ISSUE THREAD

**Issue by koenpunt** [geerlingguy/ansible-role-mysql#173]
For a more or less seamless migration I wrote a script to transform my mysql variables to the role format.

``` sh
echo 'SHOW VARIABLES WHERE Variable_Name IN("port", "bind_address", "skip_name_resolve", "datadir", "key_buffer_size", "max_allowed_packet", "table_open_cache", "sort_buffer_size", "read_buffer_size", "read_rnd_buffer_size", "myisam_sort_buffer_size", "thread_cache_size", "query_cache_size", "query_cache_limit", "max_connections", "tmp_table_size", "max_heap_table_size", "lower_case_table_names", "wait_timeout", "innodb_file_per_table", "innodb_buffer_pool_size", "innodb_log_file_size", "innodb_log_buffer_size", "innodb_flush_log_at_trx_commit", "innodb_lock_wait_timeout", "innodb_large_prefix", "innodb_file_format", "mysqldump_max_allowed_packet", "log")' | mysql -uroot -s | awk '
function human(x) {
    # only humanize when larger than 100k
    if (x<102400) {return x} else {x/=1024}
    s="kMGTEPYZ";
    while (x>=1000 && length(s)>1)
        {x/=1024; s=substr(s,2)}
    return int(x+0.5) substr(s,1,1)
}
{gsub(/^[0-9]+(\.[0-9]+)?/, human($2), $2); printf "mysql_%s: %s\n", $1, $2}'
```

This will output all but 4. Namely `bind_address`, `slow_query_log_enabled`, `slow_query_time`, and `mysqldump_max_allowed_packet`.

`bind_address` and `mysqldump_max_allowed_packet` I can understand, but why are `slow_query_log_enabled` and `slow_query_time` not named after the mysql variables like the rest? 

Would you accept a patch which does accept those to be set? With BC if you like.

**Comment by geerlingguy** [comment]
@koenpunt - I named them that way only because I wanted it to be more obvious what those two settings did/how they were related. In some cases, MySQL's default variable names can be confusing in terms of what they do, what their values should be, etc.

I'd consider a backwards-compatible fix... or even better, if you could keep the current defaults, but allow `mysql_slow_query_log` and `mysql_long_query_time` through the use of a filter like `{{ yes if mysql_slow_query_log | default('no') }}`.
