### ISSUE TITLE
Problems with Ansible 2.2.0.0

### ISSUE THREAD

**Issue by lukasged** [geerlingguy/ansible-role-mysql#175]
This morning I was trying the latest Ansible release, ``v2.2.0.0`` and this role wouldn't work for it.

I didn't have the ``mysql_packages`` variable defined, so first it failed saying that it was undefined. When I did define it, it began failing with ``'dict object' has no attribute 'stdout_lines'`` message. I think it's related to this [ansible issue](https://github.com/ansible/ansible/issues/16222).

**Comment by geerlingguy** [comment]
First issue is definitely related to: https://github.com/geerlingguy/ansible-role-postgresql/issues/7

But if you define it as an empty array (e.g. `mysql_packages: []`), then that second error should go away too? Otherwise, you might need to at least define one package.

In most cases, there should be a package (or more) defined by default, unless you're skipping the role (e.g. if you're using `postgresql` on Drupal VM or something like that).

**Comment by geerlingguy** [comment]
Hmm... I'm hitting the second error too.

**Comment by geerlingguy** [comment]
Looks like the solution of adding `|default([])` in the linked Ansible issue should fix this problem. Testing a fix now.

**Comment by geerlingguy** [comment]
Above commit should fix these errors.

**Comment by j4m3s** [comment]
This is made much more significant for us by the fact that a conditional dependency is translated into individual "when"s on all tasks within the dependency.  #15254 feature ticket refers.
