### ISSUE TITLE
Sleep not used in systemd

### ISSUE THREAD

**Issue by jp1987** [geerlingguy/ansible-role-mysql#195]
```
RUNNING HANDLER [geerlingguy.mysql : restart mysql] ****************************
 [WARNING]: Ignoring "sleep" as it is not used in "systemd"
```
While provisioning an Ubuntu 16.04 machine. Maybe we can add a check whether or not systemd is used?

**Comment by geerlingguy** [comment]
@jp1987 - That's a harmless warning... Ansible has kinda gotten a bit _too_ verbose about some things recently. Since more than half the role's users are still on init-based OSes, I'm going to leave it in for a while longer. In a couple years, I'll start stripping out all the non-systemd-default settings from my roles, but for now, I'm just used to these verbose warnings.
