### ISSUE TITLE
Add Support For SLES

### ISSUE THREAD

**Issue by brandisher** [geerlingguy/ansible-role-mysql#201]
The title pretty much says it all.  I'd be happy to contribute if you're interested in reviewing a PR.  Feel free to close if there's no plans.

**Comment by geerlingguy** [comment]
I've never personally used Suse, but if the changes required are minimal (and mostly limited to adding some vars files), then I'd be willing to support it in this role.

**Comment by brandisher** [comment]
Closing this out as SUSE management is no longer part of my role.

**Comment by CaptainSifff** [comment]
Hi all,
I've done some support for OpenSuSE in a fork of this repository over here:
https://github.com/CaptainSifff/ansible-role-mysql
the changes are mostly some vars, except the test suite. It required more work and is currently failing with an error where I'm out of ideas.
Since It's a fork of a fork, it seems that I can't directly get a pull request towards this repository.
