### ISSUE TITLE
Use 'adm' group for mysql error log

### ISSUE THREAD

**Issue by glatapoui** [geerlingguy/ansible-role-mysql#220]
In `tasks/configure.yaml`, the task _Set ownership on slow query log file (if configured)_ enforces the ownership of the log file to the user `mysql`.
This is fine, but since it is a log file, I would have hoped the group to be `adm` instead of `mysql`.
(See for example [What is the canonical use for the “sys” and “adm” groups?](https://serverfault.com/questions/485473/what-is-the-canonical-use-for-the-sys-and-adm-groups) for more info on that topic.)

Is there a reason that I miss, or could we have adm for group here ?

Thanks,
Joël.

**Comment by geerlingguy** [comment]
There's no official reasoning behind using the `mysql` user—basically, that seems to be the community convention—the few places I've seen it mentioned in docs, the files are managed by the mysql daemon run as `mysql` and when MySQL creates the files, they're created under the `mysql` user account/group as well.

MySQL (especially on Debian) does some funky things... but I kind of just roll with it. I'd rather not use `adm` for the log files because almost everything online documents the log files being owned by the user under which the daemon runs, and changing this role's default would mean this role would be doing it differently.

That said, if you wanted to find a way to make the permissions more configurable, I could work on that—but as a default, I'm not planning on switching from `mysql`/`mysql`.

**Comment by geerlingguy** [comment]
Closing this issue for now—but please feel free to file a PR and reopen if there are better ways of handling/customizing the permissions.
