### ISSUE TITLE
Check slave replication status fails because of missing replication user

### ISSUE THREAD

**Issue by roedie** [geerlingguy/ansible-role-mysql#284]
The replication user is only created on the master node in replication.yml. Since replication is not yet running on that point the replication user is not replicated to the slave node. Logging in using the replication user on the slaves will always fail.

Either the user should be created on both master and slaves or the check should be done using the root user.

I don't mind making a PR for it, but which solution do you prefer?

Sander

**Comment by roedie** [comment]
@geerlingguy I will create a PR to create the user on both.

**Comment by roedie** [comment]
@geerlingguy I've create PR #286 for this.

**Comment by razvancrainea** [comment]
Just asking, is there any reason why the `mysql_replication_user` is used to check the slave status, and not the general `login_user`? I am asking because the `login_user` should already exist and have elevated replication permissions for tasks 'Configure replication on the slave.' and 'Start replication.' to complete successfully. This way there's no need to create the replication user on the slave.
I tested this and if I comment the `login_user` and `login_password` lines in the 'Check slave replication status.' the play runs just fine.
If you guys agree with this approach and don't see any limitations, I can create a quick PR.

**Comment by roedie** [comment]
@razvancrainea Yes, that's what I had created first, but I asked what @geerlingguy prefered, and that was using the mysql_replication_user.

On the other hand, this PR has been open ever since so not sure if it will get merged anyway ;-)
