### ISSUE TITLE
systemd service does not support sleep

### ISSUE THREAD

**Issue by jesusch** [geerlingguy/ansible-role-mysql#292]
not sure if legacy sysvinit systems should be supported.
currently systemd throws the following warning
```
RUNNING HANDLER [mysql : restart mysql] ****************************************************************************************************************************************************************************************************************************************
 [WARNING]: Ignoring "sleep" as it is not used in "systemd"
```

**Comment by geerlingguy** [comment]
Right now this role still supports actively-supported init-based OSes like CentOS 6 and Ubuntu 14.04, so that needs to stay to make sure the role still works on them.

It's an innocuous warning at this point, but if that changes, I will consider removing support for init-based systems or figuring out some other solution in the future.
