### ISSUE TITLE
Suggest adding variables for character_set_server and collation_server

### ISSUE THREAD

**Issue by meersjo** [geerlingguy/ansible-role-mysql#326]
These are pretty common options, as utf8mb4 enables emoji support. Additionally, adding the variables to the playbook instead of just using include files to set them enables using them as default when creating database, too.

**Comment by websafe** [comment]
Yes, that would be great!

**Comment by jeromelefeuvre** [comment]
@geerlingguy can you merge this please ?

**Comment by fgibaux** [comment]
for info, to include files is quite easily done with the current role, using `mysql_config_include_files`:
```
mysql_config_include_files:
  - { src: charset_config.cnf, force: true }
```

and the `charset_config.cnf` file with something like:
```
[mysqld]
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
```

**Comment by meersjo** [comment]
> for info, to include files is quite easily done with the current role, using `mysql_config_include_files`:

I agree; but it's such a common option that it should be configurable out of the box.

**Comment by freephile** [comment]
I think this is a good suggestion. Please consider re-opening and implementing.

[MariaDB last changed their defaults in 11.6](https://mariadb.com/docs/server/reference/data-types/string-data-types/character-sets/setting-character-sets-and-collations#less-than-11.6) so the defaults would be relatively static, while at the same time avoiding issues for people whose database server might be old or configured to use defaults they may not even expect. 

Something that can bite you even more unexpectedly is that the server defaults for MariaDB are (or were) [different](https://mariadb.com/docs/server/server-management/install-and-upgrade-mariadb/installing-mariadb/troubleshooting-installation-issues/installation-issues-on-debian-and-ubuntu/differences-in-mariadb-in-debian-and-ubuntu#system-variables) depending on whether your OS is RHEL or Debian (because Debian packagers of MariaDB "do the right thing" and give you UTF-8 whereas 'official' MariaDB packages from MariaDB Corporation were slow to change from latin1)
