### ISSUE TITLE
Is it possible to configure Master/Master Replication with this role?

### ISSUE THREAD

**Issue by droptableuser** [geerlingguy/ansible-role-mysql#373]
Hi,
As the title says, I want to have Master Master Replication and I am at a loss on what I would need to change to make this work, I know I have to fix some values in my.cnf like the increment offsets, but otherwise I am at a loss.

Thanks for all your help.

**Comment by widhalmt** [comment]
Hi.

Did you find a solution to your question? We need to set up master-master replication as well.

**Comment by widhalmt** [comment]
I started building an "add-on" role to provide master-master replication. This role has to run after your ( @geerlingguy ) role. Since this kind of replication is known to be error-prone, I'll have to do extensive testing before offering it publicly.

If you want, I can open a pull request to integrate the changes in your role. So you could go with standard replication or master-master then. If not, I can open source the addon via our own account.

**Comment by geerlingguy** [comment]
@widhalmt - As you mention it can be quite error-prone, that's why I generally avoid it in my own deployments (I use Amazon Aurora when it's absolutely necessary... better to pay them to take care of the messy details, IMO!). I would be happy if you created an add-on role to set things up separately, and if a tweak to this role would be helpful to be able to have the follow-up role work, that would be acceptable.

But I'd rather not have the master-master code in this role.
