### ISSUE TITLE
Mysql in Debian10 doesn't create /etc/init.d/mysql

### ISSUE THREAD

**Issue by aloforte** [geerlingguy/ansible-role-mysql#379]
I stumbled upon this issue attempting to use this role to set-up Oracle Mysql-community (from oracle repositories) on Debian, and potentially on other distributions as well.

Problem is the installed packages (mysql-server, mysql-client and dependencies) does not include /etc/init.d/mysql. They happily live in the systemd world.

This results in mysql services being stopped at any subsequent run of the playbook, and iblogfile0|1 being deleted too.

Possible ways out:
- parse dpkg -l output for installed packages to validate if the requested packages are installed.
- replace the fixed string with a variable, whose default could then be /etc/init.d/mysql. That way it would at least be possible to change the file path to systemd unit, executable or other files as needed.

Thank you for the great work on ansible roles!

**Comment by jostmart** [comment]
This issue describe the same problem I found. Running the role reinstalls the database which is a no option!

Perhaps a task similar to "Get MySQL version" could be used to determine installation state?.
Looking for a mysql process is no good since it can be down, while MySQL already is installed.
Same thing looking for mountpoints or /var/lib/mysql/somefile, can also cause trouble if the filesystem are unmounted, NSF share dissapear or similar.
