### ISSUE TITLE
This task should have set no_log: True?

### ISSUE THREAD

**Issue by maurociancio** [geerlingguy/ansible-role-mysql#417]
https://github.com/geerlingguy/ansible-role-mysql/blob/0a354d6ad1e4f466aad5f789ba414f31b97296fd/tasks/secure-installation.yml#L63

**Comment by TheRojam** [comment]
there are multiple task which got this issue.
TASK [mysql : Ensure MySQL users are present.] *********************************************************************************************************************************************************************************************
fatal: [git.vebit.cloud]: FAILED! =>
  censored: 'the output has been hidden due to the fact that ''no_log: true'' was specified for this result'

sadly i can't work w/ such information.
