### ISSUE TITLE
Debian 10 CI builds are currently failing

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-mysql#422]
Debian 10 builds have been failing on the following task lately:

```
TASK [geerlingguy.mysql : Ensure MySQL is started and enabled on boot.] ********
fatal: [instance]: FAILED! => {"changed": false, "msg": "Unable to start service mariadb: Job for mariadb.service failed because a timeout was exceeded.\nSee \"systemctl status mariadb.service\" and \"journalctl -xe\" for details.\n"}
```

This is also blocking my updates to Drupal VM's CI (see https://github.com/geerlingguy/drupal-vm/issues/2109), so I'd like to at minimum get past this issue.

**Comment by geerlingguy** [comment]
Well that's annoying... I can't reproduce this locally.

**Comment by rndmh3ro** [comment]
See https://github.com/dev-sec/ansible-collection-hardening/blob/13b09a0f23ef210e19e32ecc88069746163bf8bb/.github/workflows/mysql_hardening.yml#L60 for a potential fix.

**Comment by geerlingguy** [comment]
@rndmh3ro - Ah, interesting. If that fixes it, I will shake my fist at GitHub Actions :)

**Comment by geerlingguy** [comment]
@rndmh3ro - That was it! Thanks so much.

**Comment by rndmh3ro** [comment]
You're welcome. There's a bug in the AppArmor profile for MySQL that triggers this.
Since the Github Actions run on Ubuntu with AppArmor enabled, this gets triggered. Why it is only on some Debian systems - I don't know.

**Comment by dale-c-anderson** [comment]
@rndmh3ro "a bug" ... you know which bug? is there an open issue? Anything I can find is from 5+ years ago.

**Comment by rndmh3ro** [comment]
There is not much info for this problem.
the best is this: https://bugs.launchpad.net/ubuntu/+source/mysql-5.7/+bug/1610765

Then there are multiple stackoverflow answers that describe the problem and solutions. basically the configuration for MySQL in apparmor is wrong. 

https://askubuntu.com/questions/916009/mysql-wont-start-because-of-apparmor/953988#953988

https://dba.stackexchange.com/questions/220712/apparmor-prevents-mysql-from-starting
