### ISSUE TITLE
mysql doesn't start on centos 7.0/7.1

### ISSUE THREAD

**Issue by mwiczynski-cartera** [geerlingguy/ansible-role-mysql#45]
I tried running this role on a centos 7.1 box.  mysql fails to start.  I did not change any settings/vars in the role.  If I just install mysql and start it, works fine.  Seems like whatever the defaults are in this role do not work for centos 7.

**Comment by geerlingguy** [comment]
You will need to override a few variables in your playbook, see: https://github.com/geerlingguy/ansible-role-mysql#rhelcentos-7-mariadb-configuration

This is because CentOS 7.x uses MariaDB instead of MySQL.

**Comment by mwiczynski-cartera** [comment]
Just to be clear, I want to install mysql, not mariadb.  Are you saying this role doesn't support that?

**Comment by geerlingguy** [comment]
@mwiczynski-cartera - It does; but if you want to install MySQL specifically, you'll need to add the RPM sources / repos directly prior to running this role, and that setup process isn't officially supported by this role. Since CentOS 7 / RHEL 7 has moved on to supporting MariaDB _instead of_ MySQL, this role is following suit.
