### ISSUE TITLE
Skip replication tasks

### ISSUE THREAD

**Issue by RemiLecpac** [geerlingguy/ansible-role-mysql#501]
For replication, the playbook skips all tasks.
Probably because of the following condition tasks/replications.yml:

`(slave.Is_Slave is defined and not slave.Is_Slave) or (slave.Is_Slave is not defined and slave is failed)`

The condition always returns me false.

Version:

- Ansible: 2.13.4
- community.mysql: 3.5.1
- mysql: 8.0.30
- python: 3.9.6

**Comment by VincentChantreau** [comment]
same problem here
The problem appear when I installed community.mysql collection 
It seems that they replaced Is_Slave by  Is_Replica (what a great idea to rename everything...)
So replacing the old Is_Slave variable in the replication tasks did the trick for me
Hope it can be fixed soon

**Comment by giorgioma** [comment]
See #503

**Comment by hahayusuf** [comment]
I am glad with the fix. 

However, I still seem to have the same issue of the replication tasks skipping.

When I comment out the following condition in the replication.yml file, it works as expected:

```
(slave.Is_Slave is defined and not slave.Is_Slave) or (slave.Is_Replica is defined and not slave.Is_Replica) or (slave.Is_Slave is not defined and slave.Is_Replica is not defined and slave is failed)
```

I am facing this issue with the "Configure replication" and "Start replication". I still do not understand what is causing this as the condition appears to cater for both the 'slave' and 'replica' naming convention.

**Comment by azhinu** [comment]
`Start replication` task is skipped on first run with role v4.3.3 (latest on this moment). But it runs on second run.
I think this is because replica status is checked before `Configure replication on the slave` task runs. And the role have condition `slave.Is_Replica is defined and slave.Is_Replica`, that returns `false` on first run.
But in second run replica status is `true` and `Start replication`  task runs.
So I think, we should to recheck replica status before `Start replication`  task to let complete all task in first run.
