### ISSUE TITLE
Updating postfix doesn't belong

### ISSUE THREAD

**Issue by jsumners** [geerlingguy/ansible-role-mysql#53]
I don't understand why you are updating postfix in this role. Postfix should be managed by a postfix role (which is what I do).

**Comment by geerlingguy** [comment]
That is true. I don't even remember why I originally had postfix in this role... must've been something quirky about one of the first CentOS servers I built.

I should definitely remove it (it's not even in the Debian-based setup), and then I'll do a minor version bump to indicate that people should test thoroughly before updating, since this technically could cause issues in certain configurations.

**Comment by geerlingguy** [comment]
Heck, I even have a separate postfix role: https://github.com/geerlingguy/ansible-role-postfix (and another for exim: https://github.com/geerlingguy/ansible-role-exim).

**Comment by jsumners** [comment]
Excellent. It does nothing in my configuration since I don't have the requisite extra repos added. It just makes no sense :)
