### ISSUE TITLE
Don't overwrite global configuration file

### ISSUE THREAD

**Issue by mjanser** [geerlingguy/ansible-role-mysql#82]
Couldn't the server configuration be saved in a file under `my.cnf.d` instead of the global configuration file? Then the role wouldn't have to touch a file which comes from the package, at least if `includedir` is configured there. If that's missing, it could still be added with `lineinfile`. What do you think?

**Comment by geerlingguy** [comment]
Technically, yes... but this sounds like something that would be difficult to get right cross-platform, since we'd still need to modify the main my.cnf in some (or all?) cases to make sure to include extra config in `my.cnf.d` (this role supports CentOS 6/7, Ubuntu 12/14, and Debian 7/8, along with MySQL versions from about 5.1 to 5.6/7).

**Comment by geerlingguy** [comment]
Closing and moving discussion to https://github.com/geerlingguy/ansible-role-mysql/issues/98
